-- ============================================
-- 말따먹기 퀴즈 DB 스키마
-- Supabase 대시보드 > SQL Editor 에서 실행
-- 실행 순서: 1) schema.sql  2) seed.sql
-- ============================================

-- 문항 테이블 (수정 페이지에서 직접 편집)
create table public.questions (
  id integer generated by default as identity primary key,
  section integer not null,          -- 0: 기출①, 1: 기출②, 2: 14~18년도, 3: 19~23년도
  label text not null,               -- 문항 번호 표기 (예: "3-1")
  prompt text not null,              -- 지문
  answer text not null,              -- 정답
  updated_at timestamptz not null default now()
);

-- 체크 기록 (모름/애매/정답)
create table public.marks (
  question_id integer primary key references public.questions(id) on delete cascade,
  status text not null check (status in ('wrong','unsure','correct')),
  updated_at timestamptz not null default now()
);

-- 앱 상태 (마지막 위치 등)
create table public.app_state (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- ============================================
-- RLS: 로그인한 사용자만 읽기/쓰기 가능
-- (단일 사용자 용도이므로 user_id 구분 없음)
-- ============================================
alter table public.questions enable row level security;
alter table public.marks enable row level security;
alter table public.app_state enable row level security;

create policy "authenticated full access" on public.questions
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.marks
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.app_state
  for all to authenticated using (true) with check (true);
