-- ============================================
-- 말따먹기 퀴즈 DB 스키마
-- Supabase 대시보드 > SQL Editor 에서 실행
-- 실행 순서: 1) schema.sql  2) seed.sql
-- ============================================

-- 문항 테이블 (수정 페이지에서 직접 편집)
-- 전체 사용자가 공유하는 문제은행. 지문/정답 수정은 모두에게 반영된다.
create table public.questions (
  id integer generated by default as identity primary key,
  section integer not null,          -- 0: 기출①, 1: 기출②, 2: 14~18년도, 3: 19~23년도
  label text not null,               -- 문항 번호 표기 (예: "3-1")
  prompt text not null,              -- 지문
  answer text not null,              -- 정답
  updated_at timestamptz not null default now()
);

-- 체크 기록 (모름/애매/정답) — 사용자별로 분리
create table public.marks (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id integer not null references public.questions(id) on delete cascade,
  status text not null check (status in ('wrong','unsure','correct')),
  updated_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

-- 앱 상태 (마지막 위치 등) — 사용자별로 분리
create table public.app_state (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

-- ============================================
-- RLS
--   questions : 로그인한 사용자면 누구나 읽기/쓰기 (공유 문제은행)
--   marks / app_state : 자기 행만 읽기/쓰기
-- ============================================
alter table public.questions enable row level security;
alter table public.marks enable row level security;
alter table public.app_state enable row level security;

create policy "authenticated full access" on public.questions
  for all to authenticated using (true) with check (true);

create policy "own marks only" on public.marks
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "own app_state only" on public.app_state
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
